# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: docker-compose pull # runs during prebuild
    command: | 
      docker-compose up -d
      sleep 10
      docker-compose logs | egrep -o 'https?://127[^ ]+' | tail -1


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8888
    onOpen: ignore
